added dependent job

diff --git a/.github/workflows/thirteen_workflow.yml b/.github/workflows/thirteen_workflow.yml
--- a/.github/workflows/thirteen_workflow.yml
+++ b/.github/workflows/thirteen_workflow.yml
@@ -5,8 +5,8 @@ jobs:
   run-first-command:
     runs-on: ubuntu-latest
     steps:
-      - name: Sleep 30
-        run: sleep 30
+      - name: First command
+        run: exit 1 # sleep 30
       - name: Runs on Cancelled
         if: ${{ cancelled() }}
         run: echo "Runs on Cancelled"
@@ -19,3 +19,9 @@ jobs:
       - name: Runs on Failure
         if: ${{ failure() }}
         run: echo "Runs on Failure"
+  second-job:
+    runs-on: ubuntu-latest
+    needs: run-first-command
+    if: ${{ failure() }}
+    steps:
+      - run: echo "Previous job was failed"
